export default () => ({
  ticket: {
    display: 'inline-flex',
    // 'font-size': 1rem,
    margin: '80px 0',
    textDecoration: 'none',
    width: 200,
    height: 50,
    padding: '0 10px',
    borderRadius: 3,
    border: '1px solid #ffffff',
    position: 'relative',
    zIndex: 1,
  },
  ticketInner: {
    display: 'inherit',
    alignItems: 'center',
    justifyContent: 'center',
    height: 'inherit',
    width: 'inherit',
    padding: '0 10px',
    borderRadius: '3px',
    border: '1px solid #ffffff',
    position: 'absolute',
    zIndex: 2,
    backgroundColor: '#000000',
    top: -10,
    left: -9,
  },
});
