#!/bin/bash

if test -f ./.env; then
  rm ./.env
fi

echo "
NODE_ENV=development
PATH_PUBLIC=./public
GOOGLE_UA=UA-99999999-9
PRISMIC_API=https://frontinsampa.cdn.prismic.io/api/v2
PRISMIC_TOKEN=
" >> ./.env
